ssl:
  enabled: true
  enforced: true
acme:
  enabled: true
  staging: false
  email: domains@alexolivier.me
dashboard:
  enabled: true
  domain: traefik.gcp.alxolvr.com
  auth:
    basic:
      ao: 'HERE'